# Generated by Django 5.1.3 on 2024-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_shortdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='animation_delay',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
