# Generated by Django 5.1.3 on 2024-11-15 22:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_category_icon_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('review_msg', models.CharField(default='Apply Now', max_length=1000)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('animation_delay', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'ordering': ('-created',),
            },
        ),
    ]
