# Generated by Django 5.1.3 on 2024-11-16 11:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Select', max_length=100)),
                ('famousimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('animation_delay', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('-created',),
            },
        ),
    ]
