# Generated by Django 5.1.3 on 2024-11-16 11:34

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
