# Generated by Django 5.1.3 on 2024-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='animation_delay',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
