# Generated by Django 5.1.3 on 2024-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
