# Generated by Django 5.1.3 on 2024-11-16 19:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_sitesettings_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='starting single line 200ch', max_length=200)),
                ('tagline', models.CharField(help_text='h1 big font 200ch', max_length=200)),
                ('desc', models.CharField(help_text='test under heading 500ch', max_length=500)),
                ('headerimg', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
