# Generated by Django 5.1.3 on 2024-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_feature_sitesettings_chooseus_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='animationdelay',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
