# Generated by Django 5.1.3 on 2024-11-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_feature_animationdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_starter',
            field=models.CharField(blank=True, help_text='OUR CLIENTS REVIEWS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviewsdesc',
            field=models.CharField(blank=True, help_text='reviews desc', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviewsmain',
            field=models.CharField(blank=True, help_text='What Our Clients Say', max_length=200, null=True),
        ),
    ]
