# Generated by Django 5.1.3 on 2024-11-17 09:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_sitesettings_training_starter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name of feature', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='some words about the feature', max_length=200, null=True)),
                ('desc', models.TextField(blank=True, help_text='Details of the feature', null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('animationdelay', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.TextField(blank=True, help_text='Details of the feature', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='tagline',
            field=models.CharField(blank=True, help_text='some words about the feature', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='desc',
            field=models.CharField(blank=True, help_text='test under heading 500ch', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tagline',
            field=models.CharField(blank=True, help_text='h1 big font 200ch', max_length=200, null=True),
        ),
    ]
