# Generated by Django 5.1.3 on 2024-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_training_alter_feature_desc_alter_feature_tagline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_desc',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(default=1, help_text='fviconsultants@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_starter',
            field=models.CharField(blank=True, help_text='Worlwide Offices', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='officedesc',
            field=models.CharField(blank=True, help_text='somewhat about our worldwide offices', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='officemain',
            field=models.CharField(blank=True, help_text='Explore Our Office Worldwide', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default=1, help_text='+923021108001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(default=1, help_text='+923017978598', max_length=200),
            preserve_default=False,
        ),
    ]
