# Generated by Django 5.1.3 on 2024-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shortdesc',
            field=models.TextField(default='Apply Now'),
        ),
    ]
