# Generated by Django 5.1.3 on 2024-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_category_slug_country_slug_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project',
            field=models.CharField(choices=[('visa', 'Visa Inquiry'), ('appointment', 'Appointment Request'), ('feedback', 'Feedback'), ('review', 'Review'), ('complaint', 'Complaint'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fees',
            field=models.CharField(blank=True, default='Ask Us', max_length=10, null=True),
        ),
    ]
