# Generated by Django 5.1.3 on 2024-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
