# Generated by Django 5.1.3 on 2024-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_sitesettings_fifth_phone_sitesettings_fourth_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
