# Generated by Django 5.1.3 on 2024-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_visa_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
