# Generated by Django 5.1.3 on 2024-12-04 17:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_slider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='actionurl',
            field=models.CharField(blank=True, default="{% url 'mainapp:contact' %}", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='calltoaction',
            field=models.CharField(blank=True, default='Visit Us', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='headerimg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, help_text='starting single line 200ch', max_length=200, null=True),
        ),
    ]
