# Generated by Django 5.1.3 on 2025-09-05 18:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_slider_actionurl_slider_calltoaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('applicant_name', models.CharField(db_index=True, max_length=255)),
                ('contact_number', models.CharField(db_index=True, max_length=20)),
                ('document_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('service', models.CharField(choices=[('Normal', 'Normal (2–3 weeks)'), ('Urgent', 'Urgent (1–3 working days)')], default='Normal', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receiving_method', models.CharField(choices=[('Courier Received', 'Courier Received'), ('Physically Received', 'Physically Received')], max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('applicant_address', models.TextField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('payment_received_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Courier Received', 'Courier Received'), ('Physically Received', 'Physically Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50)),
                ('expected_delivery', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['ref_no', 'applicant_name'], name='mainapp_cas_ref_no_a0e2f3_idx'), models.Index(fields=['status', 'date_created'], name='mainapp_cas_status_8e9405_idx')],
            },
        ),
    ]
