# Generated by Django 5.1.3 on 2025-09-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('Courier Received', 'Courier Received'), ('Physically Received', 'Physically Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('Courier Received', 'Courier Received'), ('Physically Received', 'Physically Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='mainapp.case')),
            ],
        ),
    ]
