# Generated by Django 5.1.3 on 2026-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_casestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='expected_delivery',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='new_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Submitted for processing', 'Submitted for processing'), ('Additional Details Required', 'Additional Details Required'), ('Processing Completed', 'Processing Completed'), ('Payment Pending', 'Payment Pending'), ('Ready for dispatch', 'Ready for dispatch'), ('Courier Dispatched', 'Courier Dispatched'), ('Physically Received by applicant', 'Physically Received by applicant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(blank=True, help_text='The title of your site', max_length=200, null=True),
        ),
    ]
